### ISSUE TITLE
BXR repo history lost before nov 2013

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-bxr#1]
The first commit in the git history has this message:

> Moving language from old to new infra.

That is, the history belonging to the old infra is lost. It should be restored.

**Comment by snomos** [comment]
With @albbas updates yesterday, all history is there, but the timestamp for everything after 2013 is bonkers, cf the following screenshot:

![image](https://user-images.githubusercontent.com/1255285/97549867-98f93a80-19d9-11eb-8e28-33756b9659af.png)

**Comment by albbas** [comment]
I see this from git-cola timeview on my Linux box:
![image](https://user-images.githubusercontent.com/75695/97550912-91826300-19d2-11eb-8b76-005d25233c1a.png)

And this is gitk:
![image](https://user-images.githubusercontent.com/75695/97551094-d1494a80-19d2-11eb-9406-8ff688b5ea35.png)

**Comment by snomos** [comment]
Seems like various GUI clients use different timestamps for displaying that info. Based on [this hint](https://stackoverflow.com/questions/3814926/git-commit-date), I did the following:

```sh
git show -s --format=%ci 23c62980295f504fa9952c2649a9f462c2d4b74a
2020-10-28 15:35:46 +0100
```

Ie **yesterday**. With `git log`, I get the expected date:

```sh
commit 23c62980295f504fa9952c2649a9f462c2d4b74a
Author: Sjur Moshagen <sjurnm@mac.com>
Date:   Tue May 5 12:46:02 2020 +0000

    [Template merge - langs/und]
    Commented out check for GTLANG_xxx variable, it is not used, and the check output is confusing to users.
```

How to change the recorded date used by `git show` I have no idea ...

**Comment by albbas** [comment]
Did this + a git push -f:
```
git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"'
```
from the second answer here: https://stackoverflow.com/questions/28536980/git-change-commit-date-to-author-date

**Comment by albbas** [comment]
git log --format=fuller shows that commitdate and authordate are synced up

**Comment by snomos** [comment]
In fact, it seems it is only the `git show -s --format=%ci` that displays the wrong date:

```sh
% git show -s 23c62980295f504fa9952c2649a9f462c2d4b74a
commit 23c62980295f504fa9952c2649a9f462c2d4b74a
Author: Sjur Moshagen <sjurnm@mac.com>
Date:   Tue May 5 12:46:02 2020 +0000

    [Template merge - langs/und]
    Commented out check for GTLANG_xxx variable, it is not used, and the check output is confusing to users.
    
    git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/bxr@190581 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

% git show -s --format=%ci 23c62980295f504fa9952c2649a9f462c2d4b74a
2020-10-28 15:35:46 +0100
```

**Comment by snomos** [comment]
It is the difference between **author date** and **committer date**:

```sh
% git show -s --format=%ai 23c62980295f504fa9952c2649a9f462c2d4b74a
2020-05-05 12:46:02 +0000
```

**Comment by snomos** [comment]
`git rebase --committer-date-is-author-date` seems to be the solution, according to [this](https://stackoverflow.com/questions/28536980/git-change-commit-date-to-author-date).

**Comment by snomos** [comment]
And now all is fine in all clients :)
